version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Manila
    open-pull-requests-limit: 4
    groups:
      production-minor-patch:
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      development-minor-patch:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: Asia/Manila
    open-pull-requests-limit: 2
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
